### ISSUE TITLE
[Mobile - 52] Parking (photo and hours)

### ISSUE THREAD

**Issue by AleksaZakrzewska** [Solvro/mobile-topwr#100]
- Change the hours in parking C-13
- Replace the photo on the map

**Comment by mikolaj-jalocha** [comment]
Do we have somewhere  map marker related to parking? 
Actually we use sth like this:

![Image](https://github.com/Solvro/mobile-topwr/assets/76820915/9c0f4c36-8d6a-4018-a6e1-3783de224b8e)

**Comment by simon-the-shark** [comment]
I believe Martyna has prepared a new parking marker? Or am I wrong?

**Comment by gry-mar** [comment]
It's on Figma for quite some time on the parking page: https://www.figma.com/design/33ofdGYbBzWvDi2MabxIc1/ToPWR-(imported)?node-id=4379-983&t=bGLFDIvf97JMfnZj-0 . I may send you the component differently but I need to know how

**Comment by mikolaj-jalocha** [comment]
Sorry for bothering you. I didn't see it before (I thought that parking's marker there was in map's photo not as a separate component)..
Again, sorry for trouble.

**Comment by gry-mar** [comment]
No problem, sorry I didn't write back earlier
