### ISSUE TITLE
[Mobile -53] Add Youtube icon?

### ISSUE THREAD

**Issue by simon-the-shark** [Solvro/mobile-topwr#101]
Maybe let's add youtube icon as well:
<img width="149" alt="Zrzut ekranu 2024-06-10 o 17 46 58" src="https://github.com/Solvro/mobile-topwr/assets/28555148/217eec08-2da2-4509-9e7c-146e5dfe360c">

**Comment by mikolaj-jalocha** [comment]
Do we have somewhere youtube icon? 
@simon-the-shark @gry-mar

**Comment by simon-the-shark** [comment]
Yeah, good point, I haven't seen any on Figma yet.

**Comment by simon-the-shark** [comment]
But basically you just gotta take some random youtube svg and paint it pomegranade - even I can do it for you in a moment. Unless we're using some specific icon package or smth @gry-mar ?

**Comment by simon-the-shark** [comment]
Also, we do have a github icon, so you can add it there as well, and we'll have some global utils for detecting url's icons this way

**Comment by simon-the-shark** [comment]
I guess smth like this will do?

<img width="387" alt="Zrzut ekranu 2024-06-15 o 00 14 39" src="https://github.com/Solvro/mobile-topwr/assets/28555148/be7c2b1f-f1b4-48a9-928f-6461f7d7735c">

**Comment by simon-the-shark** [comment]
![yt](https://github.com/Solvro/mobile-topwr/assets/28555148/389c640c-3619-4ffa-a870-bec076447ccc)
