### ISSUE TITLE
fix(about-us)/ center icons

### ISSUE THREAD

**Issue by simon-the-shark** [Solvro/mobile-topwr#125]
I'm not sure, so we can discuss, but I think those contact/social icons maybe should be a little to bottom?

maybe centered in the space that's left there

<img width="353" alt="Zrzut ekranu 2024-08-3 o 15 53 04" src="https://github.com/user-attachments/assets/accb86a4-2122-4df8-87d4-2f745f4e73fb">

**Comment by mikolaj-jalocha** [comment]
def agree
