### ISSUE TITLE
A RenderFlex overflowed by 78 pixels on the bottom in Department's detail screen. 

### ISSUE THREAD

**Issue by mikolaj-jalocha** [Solvro/mobile-topwr#142]
After some previous fixes when entering department's details screen RenderFlex error is thrown. 

![image](https://github.com/user-attachments/assets/8a3c1441-591e-4020-b262-509d2a4ef1f9)

**Comment by simon-the-shark** [comment]
So yeah, I guess we can return to previous layout or adjust department view to the new one as after mergin #181
