### ISSUE TITLE
feat/  add favorite parkings feature

### ISSUE THREAD

**Issue by simon-the-shark** [Solvro/mobile-topwr#184]
<img width="853" alt="Zrzut ekranu 2024-09-1 o 21 35 33" src="https://github.com/user-attachments/assets/fc547c51-f9c4-4f7a-822a-4b70b7e05a58">

Imo replace "info" icon with a heart button
<img width="251" alt="Zrzut ekranu 2024-09-1 o 21 37 23" src="https://github.com/user-attachments/assets/4541a4fe-508b-4415-8670-bed3ee498c3c">

"favorite" state should be saved to local memory

**Comment by mikolaj-jalocha** [comment]
@simon-the-shark  WDYT about solution involving [this](https://docs.flutter.dev/cookbook/persistence/key-value)? 

@TTomaszPWR If u're short on time, let me know. I'd do the coding with pleasure :-)

**Comment by TTomaszPWR** [comment]
> [@simon-the-shark](https://github.com/simon-the-shark) WDYT about solution involving [this](https://docs.flutter.dev/cookbook/persistence/key-value)?
> 
> [@TTomaszPWR](https://github.com/TTomaszPWR) If u're short on time, let me know. I'd do the coding with pleasure :-)

I think I have time to do it

**Comment by simon-the-shark** [comment]
@TTomaszPWR then go for it and have fun. I'll give you write permissions for the repo
