### ISSUE TITLE
Take still missing photos of few buildings

### ISSUE THREAD

**Issue by simon-the-shark** [Solvro/mobile-topwr#190]
After 4.09.2024 photo session by me and @odominiak, there's still few missing photos to take. Anyone is welcome to take some photos from this list:

**Comment by odominiak** [comment]
- [ ] M-3
- [ ] M-4
- [ ] M-6BIS
- [ ] M-11
- [ ] P-14
- [ ] T-9

**Comment by TTomaszPWR** [comment]
I added photos to solvro google drive. Projekty->ToPwr->Budynki 20.09.2024

**Comment by simon-the-shark** [comment]
Good work! Nice photos. @odominiak will place them to directus today
