### ISSUE TITLE
feat/ sort links on about us team 

### ISSUE THREAD

**Issue by simon-the-shark** [Solvro/mobile-topwr#238]

**Comment by wkrzos** [comment]
@Rei-x has told me he can take a look at it as well.

**Comment by mikolaj-jalocha** [comment]
> @Rei-x has told me he can take a look at it as well and make changes to the directus setup.

Currently, sorting logic (eg. at `StudyCircleContactSection`) is implemented locally, it doesn't depend on api setup. Similar logic needs to be implemented in `About Us` section.
