### ISSUE TITLE
change kn solvro's bg to some new one  [ON DIRECTUS]

### ISSUE THREAD

**Issue by simon-the-shark** [Solvro/mobile-topwr#244]
![image](https://github.com/user-attachments/assets/ed2afe60-e3a4-462b-baf9-8990a8176d76)
(ask Linek which one is the new one)

**Comment by wkrzos** [comment]
On it!

**Comment by wkrzos** [comment]
Done, used the Solvro 2.0 banner for now. Looks really decent.
![image](https://github.com/user-attachments/assets/b77a7e0d-bf48-4dd6-b1fa-ffbd91cc0188)

**Comment by wkrzos** [comment]
Quickly adjusted in PS
![Image](https://github.com/user-attachments/assets/57d61d51-faeb-4827-b172-5a28d7f46201)
