### ISSUE TITLE
[mobile - 13] Faculty details

### ISSUE THREAD

**Issue by AleksaZakrzewska** [Solvro/mobile-topwr#25]
When the user clicks on a faculty of choice in the "faculties" tab, information about the faculty appears.

**AC1** A map with the location of the main faculty building according to the design mockup appears.

**AC2** Information is given where the dean's office is located.

**AC3** Listed are the faculties that operate in the faculty.

**AC4** It refers to issue  _[mobile - 07] #13_  - at the bottom of the page there are scientific circles in the form of a scrollable element, pressing the selected scientific circle takes you to information about this circle

Design mockup:
![Image](https://github.com/Solvro/topwr-mobile/assets/151966564/c377744b-a246-4a55-8778-bea130911e32)

**Comment by mikolaj-jalocha** [comment]
During coding some questions came up: 

According to design:

1.  Map should be placed in the background and in the Dean's Office section compass should be displayed with infomation about detailed address



![Image](https://github.com/user-attachments/assets/9f030c02-df1f-4d22-ac06-b8e5de87f329)


2. Beneath logo address of the Department should be displayed (clickable in my opinion to enchance UX)



![Image](https://github.com/user-attachments/assets/7a5c8f49-1ae8-4983-8a6d-51088a86a347)



Our api provides this type of data regarding departments: 


![Image](https://github.com/user-attachments/assets/c3be0c20-1160-496c-a598-81fb27043f81)

- **Is the address of the department missing there along with coords for map? Or I'm missing sth (it could be that way 😝)**
- Does the `code` property reflect compass's data? (Dean's Office exact address inside building)? 
- Does the `link  `property reflect fields of study? (On the screenshot "Architektura, Gospodarka Przestrzenna")
- I belive study circles could be determined without need to include them in api response regarding deparments? 
- What is` gradient_start `and `gradient_end` property?

**Comment by simon-the-shark** [comment]
1. look like address is missing :P
2. code is like W4 or W8
3. links reflect this part I think (at least that was the intent)
<img width="587" alt="Zrzut ekranu 2024-07-14 o 21 53 50" src="https://github.com/user-attachments/assets/57b73a45-c8c3-4b4a-87d2-3c599ff555e6">

4. field of studies are definietly added but maybe they're not open for the public api (yet :))
5. same goes for departments, let me check permission on directus
6. gradient are used to show the backgrounds here
<img width="257" alt="Zrzut ekranu 2024-07-14 o 21 54 03" src="https://github.com/user-attachments/assets/7c2d09e6-6f1d-4cc2-8875-fb46f9d8ca53">

**Comment by simon-the-shark** [comment]
UPDATE
1. added address field
2. fields of studies should be public now
3. i see on playground scientific circles are not nested, but graphql still allows you to retrieve everything in single request, let me give you quick example

**Comment by simon-the-shark** [comment]
i believe something like this works on our directus api. play around with it and I think you should be able to achieve +- everyhting.
```graphql
query {
  Departments_by_id(id: 1) {
    name
    code
    logo {
      filename_disk
    }
    gradient_start
    gradient_end
    links {
      link
      name
    }
    code
    fieldsOfStudies {
      id
      name
    }
    address
  }
  Scientific_Circles(filter: {department: {id: {_eq: 1}}}  ){
    name
  }
}
```

also if you think we should change something on directus, let me know and we can arrange that. we can still adjust things there if you think something will be better some other way
