### ISSUE TITLE
fix/ certain photos are not displayed despite being present in the db

### ISSUE THREAD

**Issue by mikolaj-jalocha** [Solvro/mobile-topwr#251]
![Image](https://github.com/user-attachments/assets/23ccdb0c-7930-4797-af71-83aab99be92b)

**Comment by simon-the-shark** [comment]
cache problem 100%, probably smth either with our directus links or cachednetworkimage

**Comment by simon-the-shark** [comment]
actually still doesn't work i think

**Comment by simon-the-shark** [comment]
fixed by replacing the photos with original files from directus
