### ISSUE TITLE
[PM] Stationary vision meeting

### ISSUE THREAD

**Issue by wkrzos** [Solvro/mobile-topwr#258]
Organisation
- [x] Find a date (03.10, 18:00.)
- [x] Find a venue

Pre meeting 29.09.2024
- [x] Ola's Vision
- [x] Wojtek's Vision
- [x] Discussion on both approaches at 3pm

**Comment by simon-the-shark** [comment]
@wkrzos can this be closed?

**Comment by wkrzos** [comment]
Yep
