### ISSUE TITLE
feat/add-guide-under-development-info

### ISSUE THREAD

**Issue by wkrzos** [Solvro/mobile-topwr#262]
![Image](https://github.com/user-attachments/assets/4d6dc784-2fff-42de-95d9-4e0858e35f3d)

**Comment by simon-the-shark** [comment]
here also we need some design proposition first (I'm not sure if this will look nice)

**Comment by kamilfedio** [comment]
@simon-the-shark  @mikolaj-jalocha

1. First idea
<img width="249" alt="image" src="https://github.com/user-attachments/assets/3381474b-6611-4290-8992-cfdc03e50812">
2. Second idea
<img width="253" alt="image" src="https://github.com/user-attachments/assets/dcb5d02b-866d-4a10-aaf7-8bc2b1e3d043">

**Comment by mikolaj-jalocha** [comment]
Good work here! Imo the 1st one ;)

**Comment by simon-the-shark** [comment]
The red color is imo too agressive for this information that is not that crucial afterall

**Comment by wkrzos** [comment]
We could flip the colours? White box with stroke and the ToPWR-orange colour text? Worth a try. Great work on the design btw, love it!

**Comment by simon-the-shark** [comment]
I would go for as greyish as possible, cause it's not that crucial. Maybe just the same colors like in a normal guide tile? But that's just my opinion. What you think @wkrzos or rest?

**Comment by simon-the-shark** [comment]
But i like the concept overall

**Comment by wkrzos** [comment]
I agree, the info isn't that important as of now. Could we compare the option with the guide palette and one, where we use the same palette, but colour the text orange? If it isn't too much work ofc

**Comment by mikolaj-jalocha** [comment]
Concept overall is great. We can manipulate with colour palette and find
the best solution

**Comment by kamilfedio** [comment]
1. version without bgc color
<img width="273" alt="image" src="https://github.com/user-attachments/assets/63c8cc92-dc2f-4a95-a7c6-9be6309aa62d">
2. Default version
<img width="269" alt="image" src="https://github.com/user-attachments/assets/aef99e46-bd6f-4636-9944-83883d3e462e">
I will push and everbody can try his combination

**Comment by wkrzos** [comment]
The first one could work, although I think that the second one looks more pleasing. Could we try the second format, but with the font in orange?

**Comment by wkrzos** [comment]
Nevermind the orange colour, just read the rest of your comment and you're right, the contrast will be too annoying XD

**Comment by kamilfedio** [comment]
User experience left the chat. Im wating for rest of opinions to push pr

**Comment by simon-the-shark** [comment]
Imo either the first one but with less spacing or just the second one should be fine
