### ISSUE TITLE
[PM] insert week exceptions to Directus

### ISSUE THREAD

**Issue by simon-the-shark** [Solvro/mobile-topwr#275]

**Comment by simon-the-shark** [comment]
<img width="750" alt="Zrzut ekranu 2024-10-2 o 00 08 16" src="https://github.com/user-attachments/assets/f0639a7e-755f-4d7f-b489-723923b65ac4">

**Comment by wkrzos** [comment]
🧑‍🍳🔥

**Comment by wkrzos** [comment]
Done
![Image](https://github.com/user-attachments/assets/23a2bff4-54b6-400d-aaf4-53f062449cf7)
