### ISSUE TITLE
[PM] Collab proposal from Dział Dostępności

### ISSUE THREAD

**Issue by wkrzos** [Solvro/mobile-topwr#304]

**Comment by wkrzos** [comment]
We have to decide which of us will participate in the meeting. Szymek and I are a must. Everyone is welcome to meet but I'm afraid finding one date for all of us AND the Department may be challenging. Here's the lettucemeet link for future reference: https://lettucemeet.com/l/PgJVd

**Comment by mikolaj-jalocha** [comment]
> We have to decide which of us will participate in the meeting. Szymek and I are a must. Everyone is welcomed to meet but finding one date for all of us AND the Department may be challenging. Here's the lettucemeet link for future reference: https://lettucemeet.com/l/PgJVd

I'd like to go as well. @simon-the-shark  @wkrzos  please choose your availability, I will try to accomodate to the schedule <3

**Comment by wkrzos** [comment]
Great to hear that, I'll do that tomorrow, in the evening, when I get my next week in order B))

**Comment by wkrzos** [comment]
The meeting is set for 16.10, 10:00. We'll discuss it beforehand during our weekly.

**Comment by wkrzos** [comment]
Post-meeting notes were prepared. The next steps are being planned on our Drive.

**Comment by wkrzos** [comment]
Will turn into an ongoing collaboration. Great success, so to say <3
