### ISSUE TITLE
[PM] Review visibility on Google Play

### ISSUE THREAD

**Issue by wkrzos** [Solvro/mobile-topwr#307]
Ola has noticed that when searching for Topwr, Google Play sees it as a typo and corrects it to Topper. User then has to either click 'show searches for Topwr' or simply doesn't notice the issue. 

The issue may be simply due to our app's relatively small user base. We may try to add some synonyms or keywords or contact Google Play Support directly.

**Comment by wkrzos** [comment]
App positions at ~3rd place when searching for 'PWR', tested on 2 devices only.

**Comment by mikolaj-jalocha** [comment]
Adding accessibility support is planned for the near future. This could also impact our rankings.

**Comment by simon-the-shark** [comment]
We're on top when you search for "topwr Solvro"

**Comment by wkrzos** [comment]
False alarm, alles gut.
