### ISSUE TITLE
Revamp our project on Github Projects

### ISSUE THREAD

**Issue by wkrzos** [Solvro/mobile-topwr#316]
- [x] #317
- [x] #318
- [x] #319
- [x] #320

**Comment by wkrzos** [comment]
I'm wondering whether to use the label 'epic' or the milestones to group bigger pieces of work. Both have their advantages and disadvantages. I'd like to discuss it on the closest weekly. The milestones are great for filtering the pieces of work, but I don't think that they can be kept private. This could create quite a clutter for people simply looking through our repo. We'd have to create a separate repo for just those milestones, which would be a mess.

**Comment by simon-the-shark** [comment]
It's also possible to filter those issues that do not have certain label. For example we can filter out "PM" ones

**Comment by wkrzos** [comment]
I set up some basic filters in each view yesterday. But I'm unsure if they are global or specific for each team member.
