### ISSUE TITLE
Marshall

### ISSUE THREAD

**Issue by wkrzos** [Solvro/mobile-topwr#328]
**Marshall Plan** - Take care of what we have. Fix the remaining issues. Continoue with the user feedback. In the meantime, compose documents on the project's future. This phase is crucial for the longevity of ToPWR and future maintainability. We have to make sure, that the project will be passed down to future members as smoothly as it is possible. This includes documentation of our code, PM documents, ongoing issues, goal of the app, and many more.
- [x] #321
- [x] #322
- [x] #323
- [x] #324
- [x] #325
- [x] #326
- [x] #327
- [ ] #339

**Comment by simon-the-shark** [comment]
One central topwr handbook is needed as well that will describe what we use and how we use and where you can find more detailed docs on the specific topics

**Comment by wkrzos** [comment]
> One central topwr handbook is needed as well that will describe what we use and how we use and where you can find more detailed docs on the specific topics

I love this idea!

**Comment by wkrzos** [comment]
Mr. Shark, We Have to Cook
