### ISSUE TITLE
Tomasz Finke collab proposal on SKS

### ISSUE THREAD

**Issue by wkrzos** [Solvro/mobile-topwr#343]

**Comment by czaja307** [comment]
@simon-the-shark @wkrzos I think we can close this one, as the wrapper for SKS users has been completed. Unless there is something bigger that i don't know of.

**Comment by simon-the-shark** [comment]
We should prolly write him back some email

**Comment by wkrzos** [comment]
Surely, the guy helped us a lot and I'm sure he'll be happy to see his work in use.

**Comment by wkrzos** [comment]
Closing the issue as this epic is contained in another epic #359.
