### ISSUE TITLE
feat/ sks menu and activity

### ISSUE THREAD

**Issue by wkrzos** [Solvro/mobile-topwr#359]
quick asana test: https://app.asana.com/0/1208841821696506/1208852725783700

**Comment by simon-the-shark** [comment]
add sks menu view, that fetches menu from our API: https://api.topwr.solvro.pl/api/v1/meals![Image](https://github.com/user-attachments/assets/359fb16b-826f-4e17-b806-f774fb1712a3)

1. header, smth like this (but with last update in format "ten min ago" ![Image](https://github.com/user-attachments/assets/1f6c9a9d-4a55-4ba9-9659-e930d2569ede)

2. expandable tiles with categories:
![Image](https://github.com/user-attachments/assets/fb320b15-81c6-4491-ae5a-382b6769e34d)

3. food item tiles, more or less like this, but with price/grams swapped and grams in grey:![Image](https://github.com/user-attachments/assets/c97067dc-d978-4fff-a98d-fd86ec683bdc)

**Comment by wkrzos** [comment]
Moved the issue described to #385
