### ISSUE TITLE
fix/ align appbar in horizontal mode

### ISSUE THREAD

**Issue by odominiak** [Solvro/mobile-topwr#376]
![Image](https://github.com/user-attachments/assets/88a76b2b-7aeb-49ba-b248-270350557c82)

**Comment by Rejfi** [comment]
It looks like it is non-reproducible. I try get the same result on emulator with the same dimension and physical device but every time everything is fine. 

![Image](https://github.com/user-attachments/assets/dc93aa4e-d49d-4266-b6d4-2edd2a2420a9)
@simon-the-shark

**Comment by simon-the-shark** [comment]
Yeah, the issue is probably due to camera island, so you have to simulate this somehow or use a device with some funny camera shape on top

**Comment by Rejfi** [comment]
Is there information about phone model?

**Comment by odominiak** [comment]
Redmi Note 8 Pro

**Comment by Rejfi** [comment]
Oke, on Xiaomi 12X we have the same behaviour. TopAppBar by default add safe paddings and move logo to the right in landscape mode.
