### ISSUE TITLE
feat/ come up with and implement for sks menu a simple framework for caching REST endpoints

### ISSUE THREAD

**Issue by simon-the-shark** [Solvro/mobile-topwr#382]
now we have a cache system based on `grapql` lib and a custom wrapper that introduces TTL to it and remote flush.

Ideally in the future we want to replace `graphql` and `graphql_codegen` with a) custom models (not generated ones) and b) fully custom caching / caching from some library that is appriorate for REST endpoint.

new feature that we don't have at the moment could be some custom checks for cache validity

this is big design choice. You can consult @simon-the-shark  or @mikolaj-jalocha  at any point and quite frequently.

for now we want to lay foundations for wider use in the app and implement it for sks menu repository (but the refresh must be 15 min after last refresh on the api side, so some custom cache validity check could be usefull)

**Comment by czaja307** [comment]
@simon-the-shark technical suggestion - i think you should update the refresh interval from 15 to 5 minutes, since we increased the frequency on our side

btw should i be concerned about this or is this entirely on the mobile side?

**Comment by simon-the-shark** [comment]
So after second thought, the menu prolly will be refreshed only with pull to refresh?

**Comment by simon-the-shark** [comment]
But caching for REST is still crucial

**Comment by simon-the-shark** [comment]
@tomasz-trela , my quick thoughts/detailed spec on the subject:
2. rest cache ma polegać w skrócie na tym że wrzucamy dane do lokalnej bazki danych i potem przy kolejnym requescie tego typu wyciągamy dane z bazki jeśli są jeszcze valid i je zwracamy. Jak nie są valid to uderzamy na API i potem aktualizujemy bazkę żeby mieć znowu valid dane przez jakiś czas
3. TTL: musimy móc jakoś konfigorować TTL po którym dane będą nieważne
4. nice to have: dodatkowe validity checki - oprócz TTLa fajnie by było móc dodawać jakieś customowe warunki (np. przyjmuj po prostu funckję zwracająca boola)
5. forma: najlepiej funkcja/klasa/extension które będzie można łatwo użyć w każdym z repozytoriów. Musi przyjmować parametry (takie mi teraz przyszły na myśl): TTL, URL na który uderzamy (potraktowałbym też go jako klucz który identyfikuje ściągnięte dane w jakiś sposób), schema do parsowania (np. freezed model albo coś takiego). Mam nadzieje że będzie to technicznie wykonalne
Dodatkowe uwagi:
- do TTLu możesz spróbować lekko zmodyfikować aktualny TTLManager (czy jakos tak), ale większość logiki powinno być tam git
- zamiast aktualnego TTLKey (czy jakoś tak) przeszedł bym na URLe
- idealnie chcielibyśmy uniknąć osobnego definiowania modeli do bazki i do api - wolałbym musieć definiować tylko jeden model/scheme (nie musi być freezed, jak znajdziesz coś lepszego tego typu do tego use case’a to spoko)
- nie używaj shared preferences, wolałbym normalną bazkę, prawdopodbnie raczej NoSQLową np. Hive albo Isar
- https://docs.flutter.dev/get-started/fundamentals/local-caching
- możesz przeczesać czy są jeszcze jakieś cool paczki do tego przypadku ale customowe rozwiązanie też będzie gito (możnaby wtedy pomyśleć żeby wypuścić to jako customową paczkę)


we can still meet up before the weekly and discuss any questions or ideas
