### ISSUE TITLE
chore/ update SKS's menu URL and adjust models to the new response

### ISSUE THREAD

**Issue by mikolaj-jalocha** [Solvro/mobile-topwr#401]
- endpoint of sks's menu has changed, please update it: `https://sks-api.topwr.solvro.pl/api/v1/meals/current`
- structure of the response's chagned as well:
```
{
"meals": [],
"isMenuOnline": false
}
```

- Where `meals `contains lists of foods and `isMenuOnline `tells us if data is from cache or not. Previously only meals were available.
- **Please adjust the code for new response. If `isMenuOnline` equals `true` empty list should be passed down the stream**
- Please see docs [here](https://sks-api.topwr.solvro.pl/api/v1/docs)

![Image](https://github.com/user-attachments/assets/20cfe6a1-a5fe-4361-b90d-b9f7167ec3b4)

**Comment by czaja307** [comment]
https://sks-api.topwr.solvro.pl/api/v1/docs
