### ISSUE TITLE
Organise the first weekly for each team

### ISSUE THREAD

**Issue by wkrzos** [Solvro/mobile-topwr#404]
Try to incorporate some ice-breaking activities; and, of course, don't forget to say hi ;)
- [x] Mobile
- [x] Backend
- [x] PMxTL

**Comment by wkrzos** [comment]
Waiting for the results now

**Comment by czaja307** [comment]
any interesting ideas for mini-integration?

**Comment by wkrzos** [comment]
Oh, one last thing: asking your team members to turn their webcams on is probably the top 1 thing that can boost their immersion during the meeting, I'd really recommend that.
