### ISSUE TITLE
feat/ navigation aware pop button

### ISSUE THREAD

**Issue by thesun901** [Solvro/mobile-topwr#438]

**Comment by thesun901** [comment]
![Image](https://github.com/user-attachments/assets/e68a624e-171d-4e4f-bb53-a1a520439ea0)

**Comment by odominiak** [comment]
@thesun901 Are U sure that’s the task you’re working on right now 🧐

**Comment by thesun901** [comment]
> [@thesun901](https://github.com/thesun901) Are U sure that’s the task you’re working on right now 🧐

Yeah pretty sure 😌 (i already finished my last one) It appeared to be bigger issue to solve than expected tho (but lucky for me @simon-the-shark helps me a little bit)

**Comment by thesun901** [comment]
Btw @odominiak it's you who noticed this bug right? Good job (unfortunately I stole it as my task 🔥)
