### ISSUE TITLE
fix/ investigate and fix map views

### ISSUE THREAD

**Issue by odominiak** [Solvro/mobile-topwr#457]
![Image](https://github.com/user-attachments/assets/a0cd671d-dd03-47bb-a991-c326b9d32424)
![Image](https://github.com/user-attachments/assets/b023de77-8c79-4968-8b15-5bfd30761749)

**Comment by simon-the-shark** [comment]
So this is generally cursed, but kinda crucial to fix. You need to investigate and fix the cause. At the moment, problematic detected cases are:
1. rotating devices (see above)
2. using our feedback form in specific manner (see above)

good luck

**Comment by simon-the-shark** [comment]
Probably the problem is realted to some rebuilds that cause some crashes. Maybe state management related?
Just guessing here
