### ISSUE TITLE
[mobile-18] Make the re-design of the Science Clubs View

### ISSUE THREAD

**Issue by AleksaZakrzewska** [Solvro/mobile-topwr#46]
As a user, I would like to see basic information about study circles from official University page: https://dzialstudencki.pwr.edu.pl/organizacje-studenckie/wykaz-uczelnianych-organizacji-studenckich/kola-naukowe

**AC 1** If a research circle has contact information on the page, then as a user I want to see a link with the appropriate icon 
**AC 2** Information to be updated about once a semester- manually

If possible:
**AC 3** As a user, I would like to be able to select the type of student organization first and then the list pertaining to the type.
![Image](https://github.com/Solvro/mobile-topwr/assets/151966564/c2e13f62-33d5-4ad0-81ca-85cca7a07b9f)

design can be analogous to the selection of faculty (TO BE DONE) @gry-mar 

![Image](https://github.com/Solvro/mobile-topwr/assets/151966564/4ca04d40-d880-480d-b5cf-7a68dfa42dd1)

**Comment by simon-the-shark** [comment]
**NOTE**: The latest decisions indicated a 'filters' section similar to the one used for selecting products in an online store. It must definitely include filtering by tags, departments, and types of organizations (4 as mentioned above) – additional filters can be added if there are ideas for them.
