### ISSUE TITLE
feat (digital-guide): implement report change functionality

### ISSUE THREAD

**Issue by mikolaj-jalocha** [Solvro/mobile-topwr#471]
- UI has been implemented. After click button should redirect to an e-mail app with appropriate topic and address already defined. Please remember about internalization. 

![Image](https://github.com/user-attachments/assets/4ab80705-c756-416f-bf6c-b59470a419e6)

**Comment by simon-the-shark** [comment]
for this we prolly need to write an email with the question first

**Comment by mikolaj-jalocha** [comment]
Or as a placeholder use solvro's mail
