### ISSUE TITLE
feat (digital-guide): add evacuation tile

### ISSUE THREAD

**Issue by mikolaj-jalocha** [Solvro/mobile-topwr#472]
- Add tile along with content for evacuation plans for a  given building. 
- Map should be implemented as well (photo and fullscreen after tap)
- Detailed mock can be found on our Figma
- Please write short documentation about api's endpoints that you used, place it in readme file inside data package.

Please take into consideration content of the following mail: 

![Image](https://github.com/user-attachments/assets/7eae34c0-b567-449a-813c-23fcabe2052b)

![Image](https://github.com/user-attachments/assets/d94304a2-e078-47d2-843e-edd8488f16b7)

<img src=https://github.com/user-attachments/assets/d68090f3-3ab1-486a-8133-3d543a12868a width=200 />

**Comment by simon-the-shark** [comment]
You don;t need to implement nav links to "przejście z budynku c3 na parterze" - just show them and implementing those views will be a separte task for the future
