### ISSUE TITLE
[mobile -22] Prepare a promotion plan

### ISSUE THREAD

**Issue by AleksaZakrzewska** [Solvro/mobile-topwr#53]
Let's talk to the board about promotional opportunities, make a plan, brainstorm how to promote this to students, how to reach out to students, how to encourage.

**Comment by simon-the-shark** [comment]
🔥 🔥 🚒 🔥 🔥

**Comment by simon-the-shark** [comment]
@jmorawiecpwr can we consider this task closed as part of `v.1.0.0` milestone?

**Comment by wkrzos** [comment]
To the best of my knowledge, the plan has been prepared and the issue can be closed. We should move to its implementation.

**Comment by wkrzos** [comment]
Just confirmed it. Closing the issue and creating #250
