### ISSUE TITLE
[Mobile - 30] Android: back button/gesture kills app 

### ISSUE THREAD

**Issue by simon-the-shark** [Solvro/mobile-topwr#64]
It looks a bit like a problem with flutter or embedder or smth: https://github.com/flutter/flutter/issues/117061
But maybe someone can fix this with some config

**Comment by mikolaj-jalocha** [comment]
@simon-the-shark  Excellent job! I especially like the way you organized logic needed to determine if pop's possible. Very elegant in my opinion :-) I tested in on Android 11, works perfectly fine. 

Before, I didn't know about `pigeon `pacakge. It's defenitelly very usefull and I'm sure we will need to use it sooner or later (eg. with platforms widget future? ), thanks for showing me that :-) I'm looking forward to put it into the practice.  In our current case, I also agree, it's definitely overkill. 

Btw, I thought we could post our solution at the bug's thread maybe it'd help someone?

**Comment by simon-the-shark** [comment]
Yeah, you can merge.

About sharing the solution, it's a great idea and I've thought about it too.

We can obviosly share link to our PR, since the repo is public now.

But ideally, it would be nice to paste there some minimal step-by-step reproducible solution.

Maybe we can play round with a fresh flutter project and prepare solution for simpler situation without nested navigator (unless the nested navigator is the problem here)

I'm looking forward to sharing the solution too, so I can prepare something later today, but don't want to take away the fun from you, so if you want and have a free moment you can prepare something and I'll just look into it.

**Comment by mikolaj-jalocha** [comment]
I should craft something max till tomorrow (and will do  it with fun :)) ) but feel free if you have time to spare to prepare sth today and maybe I could be some help later.
