### ISSUE TITLE
[Mobile - 39] Info page

### ISSUE THREAD

**Issue by AleksaZakrzewska** [Solvro/mobile-topwr#81]
Prepare info page

**Comment by simon-the-shark** [comment]
as a user I want to have info page, that consist of list of FAQ_Types and "About me" tile

![Image](https://github.com/Solvro/mobile-topwr/assets/28555148/65d7a736-adb3-4c88-8502-7b04d59b4895)

**Comment by simon-the-shark** [comment]
https://www.figma.com/design/33ofdGYbBzWvDi2MabxIc1/ToPWR-(imported)?node-id=1630-2095&t=07OR1T7AwWRxoBkw-1
