### ISSUE TITLE
[Mobile - 46] Nicely rendered Sci Clubs descriptions

### ISSUE THREAD

**Issue by simon-the-shark** [Solvro/mobile-topwr#90]
as a user I want nicely looking, formatted descrptions:

1. either fix this html with some renderer:
![image](https://github.com/Solvro/mobile-topwr/assets/28555148/e3517f20-8190-4f35-a3c8-0767049c7a00)

2. alternatively, we can change this on backend to markdown instead and use some markdown renderer

**Comment by mikolaj-jalocha** [comment]
What about using [this](https://pub.dev/packages/flutter_widget_from_html)?

**Comment by simon-the-shark** [comment]
Sure, i believe there are few possible packages that render html so we can use one of them
