### ISSUE TITLE
Do we wanna sort buildings in some way?

### ISSUE THREAD

**Issue by simon-the-shark** [Solvro/mobile-topwr#98]

**Comment by kamilfedio** [comment]
I guess we can make something like ranking, from most import/useful to common, eg. C-13, next buildings with secretariat for departments etc.

**Comment by simon-the-shark** [comment]
Yeah, it's an idea. Alternatively, we can just sort them alphabetically from A1 to T-something. Cause at the moment they are in order of insertion into the system.

**Comment by simon-the-shark** [comment]
Your idea have this one potencial that C-13 is indeed a nice representative building, so it would look nice at the top. If you remind us, we can discuss this on weekly today

**Comment by simon-the-shark** [comment]
As we have just established: NO
